project_id = "qqrvezuesxaappslfvrh"

[functions.nfc-meal-pickup]
verify_jwt = false

[functions.delete-user]
verify_jwt = true

[functions.ai-help-assistant]
verify_jwt = true

[functions.manage-user-role]
verify_jwt = true

[functions.send-employee-reminder]
verify_jwt = false

[functions.send-admin-menu-alert]
verify_jwt = false